# Generated by Django 4.0 on 2024-01-28 15:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_contact_alter_news_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 28, 15, 25, 10, 689019, tzinfo=utc)),
        ),
    ]
