# Generated by Django 4.0 on 2024-01-31 03:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_news_view_count_alter_news_publish_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='view_count',
        ),
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 3, 22, 56, 103696, tzinfo=utc)),
        ),
    ]
