# Generated by Django 4.0 on 2024-01-31 03:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0006_remove_news_view_count_alter_news_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 3, 27, 28, 390871, tzinfo=utc)),
        ),
    ]
